[package]
name = "scrape_data_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tungstenite = "0.21.0"
actix-web-actors = "4.3.0"
